---
title: "2018-12-12"
output: html_notebook
---
```{r}
library(readr)
libraryData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/library100_102.csv")
```

```{r}
libraryData$書籍館藏地 %>% as.factor %>% levels -> storageLocations
storageLocations
```

```{r}
i<-1
storageLocation_i <- storageLocations[i] 
numericalIndexForSubsample<-which(libraryData$書籍館藏地==storageLocation_i)
subsample_i <- libraryData[numericalIndexForSubsample,]
borrowCount_i <- nrow(subsample_i)
```

```{r}

allBorrowCount <- vector("numeric",18)
i<-1
  storageLocation_i <- storageLocations[i] 
  numericalIndexForSubsample<-which(libraryData$書籍館藏地==storageLocation_i)
  subsample_i <- libraryData[numericalIndexForSubsample,]
  borrowCount_i <- nrow(subsample_i)
  allBorrowCount[[i]]<-borrowCount_i
```

```{r}
libraryData %>%
  group_by(書籍館藏地) %>%
  summarise(
    borrowCount=length(學號)
  ) -> result
result
```

```{r}
libraryData %>%
  group_by(學院,入學年) %>%
  summarise(
    borrowCount=length(學號)
  ) -> result2
result2
```

